"""Uncertainty analysis over a statement that was read from a scan.

This layer never rewrites a printed figure. It answers three questions the deterministic reader cannot:

  * Which printed line is the one that does not fit? A weighted solve with the statement's own identities as soft
    constraints gives a residual per identity and an outlier probability per figure.
  * If a figure is a misread, what was it most likely printed as? The scan confuses digits in a few specific ways,
    so candidates are generated by undoing those confusions and scored against the identities.
  * How much does the uncertainty matter to the conclusion? Monte Carlo propagates the reading uncertainty into the
    gap between the proposal's allotment and the actual net pay change, and reports a credible interval.

Every quantity produced here is labelled fitted, posterior or modelled. A fitted value is never reported as a
figure read from the payroll, and an exception is never closed by a model: it becomes better described.

The formulation follows the review of this design: observations are Gaussian about the latent value with variances
calibrated from pages whose true figures are known; identities are soft constraints whose variance is the rounding
variance of the amounts in them; the solve is iteratively reweighted so one wild reading cannot drag the fit.
"""
import json, os, math, re
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional

ROUNDING_SD = 0.005 / math.sqrt(3.0)      # a figure printed to the cent, uniform within its rounding interval
DEFAULT_SD = 0.75                         # a read figure with no calibration behind it
MISSING_SD = None                         # a figure that was not read has no observation, not a wide one

FIELDS = ('gross', 'federal', 'state', 'social_security', 'medicare', 'retirement', 'retirement_insurance',
          'other_total', 'total_deductions', 'net_pay', 'taxable_wages', 'medicare_gross', 'premium', 'fee',
          'reimbursement')

# Each identity is (name, {field: coefficient}), asserted to equal zero.
IDENTITIES = (
    ('gross less total deductions is net pay',
     {'gross': 1.0, 'total_deductions': -1.0, 'net_pay': -1.0}),
    ('the deduction lines add to the deduction total',
     {'total_deductions': 1.0, 'federal': -1.0, 'state': -1.0, 'social_security': -1.0, 'medicare': -1.0,
      'retirement': -1.0, 'retirement_insurance': -1.0, 'other_total': -1.0}),
    ('federal taxable wages are gross less the pre-tax reductions',
     {'gross': 1.0, 'retirement': -1.0, 'premium': -1.0, 'taxable_wages': -1.0}),
    ('medicare wages are gross less the pre-tax reductions that also reduce FICA wages',
     {'gross': 1.0, 'premium': -1.0, 'medicare_gross': -1.0}),
)

CALIBRATION_PATH = os.environ.get('CALIBRATION_PATH') or os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'calibration.json')


@dataclass
class Fit:
    values: Dict[str, float] = field(default_factory=dict)          # fitted value per field
    sd: Dict[str, float] = field(default_factory=dict)              # standard error of the fit
    observed: Dict[str, float] = field(default_factory=dict)        # what was read
    residuals: Dict[str, float] = field(default_factory=dict)       # per identity
    outlier: Dict[str, float] = field(default_factory=dict)         # posterior probability the reading is wrong
    identifiable: Dict[str, bool] = field(default_factory=dict)
    note: str = ''

    def as_dict(self):
        return asdict(self)


def load_calibration(path=CALIBRATION_PATH):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return {}


def observation_sd(field_name, rec=None, cal=None):
    """The standard deviation to give a read figure, from pages whose true figures are known where possible."""
    cal = cal if cal is not None else load_calibration()
    per = (cal.get('field_sd') or {})
    sd = per.get(field_name)
    if sd is None:
        sd = per.get('default', DEFAULT_SD)
    if rec is not None:
        if rec.get(field_name + '_corrected') or rec.get(field_name + '_derived'):
            sd = max(sd, (cal.get('derived_sd') or {}).get(field_name, sd * 2))
        if rec.get('from_geometry') and field_name in (rec.get('from_geometry') or []):
            sd = min(sd, (cal.get('geometry_sd') or {}).get(field_name, sd))
    return float(sd)


def _identity_sd(coeffs, present):
    """A constraint over k figures printed to the cent carries k rounding variances."""
    k = max(1, sum(1 for f in coeffs if f in present))
    return math.sqrt(k) * ROUNDING_SD * 2 + 0.01      # a cent of slack for the provider's own rounding


def solve(rec, cal=None, huber_k=2.5, iterations=4):
    """Fit the latent figures of one statement to its printed figures and its own identities.

    Returns a Fit. Fields with no observation are fitted only where the identities determine them, and are marked
    not identifiable otherwise: an unread figure must not acquire a confident value out of nowhere.
    """
    try:
        import numpy as np
    except Exception:
        return Fit(note='numpy is not available, so no uncertainty analysis was done')
    cal = cal if cal is not None else load_calibration()
    obs = {f: float(rec[f]) for f in FIELDS if rec.get(f) is not None}
    if len(obs) < 3:
        return Fit(observed=obs, note='too few figures were read to fit anything')
    idx = {f: i for i, f in enumerate(FIELDS)}
    n = len(FIELDS)

    rows, rhs, weights, tags = [], [], [], []
    for f, y in obs.items():
        r = [0.0] * n
        r[idx[f]] = 1.0
        rows.append(r); rhs.append(y); weights.append(1.0 / max(observation_sd(f, rec, cal), 1e-6) ** 2)
        tags.append(('obs', f))
    for name, coeffs in IDENTITIES:
        if sum(1 for f in coeffs if f in obs) < 2:
            continue
        r = [0.0] * n
        for f, c in coeffs.items():
            r[idx[f]] = c
        rows.append(r); rhs.append(0.0)
        weights.append(1.0 / max(_identity_sd(coeffs, obs), 1e-6) ** 2)
        tags.append(('identity', name))
    # a field with no observation and no identity touching it is pinned to zero only to keep the system solvable;
    # it is reported as not identifiable, never as a fitted figure
    touched = {f for _, c in IDENTITIES for f in c} | set(obs)
    for f in FIELDS:
        if f not in touched:
            r = [0.0] * n
            r[idx[f]] = 1.0
            rows.append(r); rhs.append(0.0); weights.append(1e-6); tags.append(('pin', f))

    A = np.array(rows, dtype=float)
    b = np.array(rhs, dtype=float)
    w = np.array(weights, dtype=float)

    x = None
    for _ in range(iterations):
        W = np.sqrt(w)
        Aw = A * W[:, None]
        bw = b * W
        x, *_ = np.linalg.lstsq(Aw, bw, rcond=None)
        resid = A @ x - b
        # reweight in the Huber manner: a reading far from the fit loses influence rather than dragging it
        scaled = resid * np.sqrt(w)
        w = np.array([wi if abs(s) <= huber_k else wi * huber_k / abs(s)
                      for wi, s in zip(weights, scaled)], dtype=float)

    resid = A @ x - b
    scaled = resid * np.sqrt(np.array(weights))
    # standard errors from the (weighted) normal equations
    try:
        cov = np.linalg.pinv((A * np.array(weights)[:, None]).T @ A)
        sd = np.sqrt(np.clip(np.diag(cov), 0, None))
    except Exception:
        sd = np.zeros(n)

    # identifiability: a field is identified if removing its observation still leaves the system determining it
    rank_full = np.linalg.matrix_rank(A * np.array(weights)[:, None] > 0)
    fit = Fit(note='')
    for f in FIELDS:
        i = idx[f]
        col_used = any(abs(A[r][i]) > 0 and tags[r][0] != 'pin' for r in range(len(rows)))
        fit.identifiable[f] = bool(col_used)
        if f in obs or col_used:
            fit.values[f] = round(float(x[i]), 2)
            fit.sd[f] = round(float(sd[i]), 4)
    fit.observed = obs
    for r, (kind, name) in enumerate(tags):
        if kind == 'identity':
            fit.residuals[name] = round(float(A[r] @ x - b[r]), 2)

    # A test that needs no unread line. Whatever else the statement prints, the deduction lines that were read
    # cannot add up to more than gross less net pay: the rest of that difference belongs to lines the scan did not
    # read. When they do exceed it, one of the readings is wrong, and by how much is known exactly. An identity
    # with an unread member cannot do this work, because the solver is free to absorb the error into the unread
    # figure and nothing then looks out of place.
    DEDUCTIONS = ('federal', 'state', 'social_security', 'medicare', 'retirement', 'retirement_insurance',
                  'other_total', 'premium', 'fee')
    excess = None
    if obs.get('gross') is not None and obs.get('net_pay') is not None:
        room = obs['gross'] - obs['net_pay']
        read_deductions = sum(obs[f] for f in DEDUCTIONS if f in obs)
        if read_deductions - room > float(cal.get('material_residual') or 1.0):
            excess = round(read_deductions - room, 2)
            fit.residuals['the deduction lines read exceed gross less net pay'] = excess
            fit.note = (fit.note + ' ' if fit.note else '') + (
                f'the deduction lines read add to {read_deductions:,.2f}, which is {excess:,.2f} more than the '
                f'{room:,.2f} between gross and net pay, so at least one of them is not the printed figure')

    # A zero is the reading a scan produces when it loses a figure altogether, and a zero is never infeasible, so
    # the test above cannot see it. Where the statement prints a deduction total, the lines read must account for
    # it: if they fall short by a material amount and one of them was read as nothing, that line is the suspect.
    shortfall = None
    if obs.get('total_deductions') is not None:
        parts = [f for f in DEDUCTIONS if f in obs and f != 'total_deductions']
        short = round(obs['total_deductions'] - sum(obs[f] for f in parts), 2)
        zeros = [f for f in parts if abs(obs[f]) < 0.005]
        if short > float(cal.get('material_residual') or 1.0) and zeros:
            shortfall = short
            fit.residuals['the deduction lines read fall short of the printed deduction total'] = short
            fit.note = (fit.note + ' ' if fit.note else '') + (
                f'the lines read fall {short:,.2f} short of the printed deduction total of '
                f'{obs["total_deductions"]:,.2f}, and ' + ', '.join(z.replace('_', ' ') for z in zeros) +
                ' was read as nothing, which is what a scan produces when it loses a figure')

    # Which reading is the one at fault. Two parts: on its own, is this reading more consistent with ordinary
    # rounding or with a misreading (a two component mixture); and among the readings that share a failing
    # identity, which one explains the failure best. The second part is what a reader actually wants, because an
    # identity that does not tie makes every figure in it look suspect.
    pi = float((cal.get('outlier_rate') or 0.08))
    K = float((cal.get('outlier_scale') or 40.0))
    own = {}
    for r, (kind, name) in enumerate(tags):
        if kind != 'obs':
            continue
        s = abs(float(scaled[r]))
        good = (1 - pi) * math.exp(-0.5 * min(s * s, 1e4))
        bad = pi * (1.0 / K) * math.exp(-0.5 * min((s / K) ** 2, 1e4))
        own[name] = bad / max(good + bad, 1e-300)
    for f in obs:
        own.setdefault(f, 0.5)
    blame = {f: 0.0 for f in own}
    material = float(cal.get('material_residual') or 1.0)
    for name, coeffs in IDENTITIES:
        r = fit.residuals.get(name)
        if r is None or abs(r) <= material:
            continue                      # a residual of pennies is the provider's own rounding, not a misreading
        members = [f for f in coeffs if f in own]
        if not members:
            continue
        # a reading whose alternative readings could absorb this residual takes more of the blame
        share = {}
        temp = float(cal.get('blame_temperature') or 5.0)      # dollars
        for f in members:
            alts = candidates(obs[f], cal)
            need = abs(r)
            close = min((abs(abs(v - obs[f]) - need) for v in alts), default=need)
            share[f] = math.exp(-close / max(temp, 0.5))
        tot = sum(share.values()) or 1.0
        for f in members:
            blame[f] = max(blame[f], share[f] / tot)
    # Blame is what a reader wants: among the figures in an identity that does not tie, which one is most likely
    # the misreading. The standalone mixture probability saturates once the residual is large, so it is used only
    # to scale the blame, never on its own.
    if shortfall is not None:
        zeros = [f for f in DEDUCTIONS if f in obs and abs(obs[f]) < 0.005]
        for f in zeros:
            blame[f] = max(blame.get(f, 0.0), 0.9 if len(zeros) == 1 else 0.9 / len(zeros))
    if excess is not None:
        # Blame goes to the deduction lines whose alternative readings could account for the excess, in proportion
        # to how closely they could account for it.
        members = [f for f in DEDUCTIONS if f in obs]
        share = {}
        temp = float(cal.get('blame_temperature') or 5.0)
        for f in members:
            alts = candidates(obs[f], cal)
            close = min((abs((obs[f] - v) - excess) for v in alts), default=excess)
            share[f] = math.exp(-close / max(temp, 0.5))
        tot = sum(share.values())
        if tot < 1e-9:
            # No alternative reading of any one line accounts for the excess, so which line is at fault cannot be
            # said. The excess is still a fact about the page: blame is spread by size, because a large line can
            # be wrong by a large amount, and the finding stands on the infeasibility rather than on the blame.
            mag = {f: abs(obs[f]) for f in members}
            total_mag = sum(mag.values()) or 1.0
            for f in members:
                blame[f] = max(blame.get(f, 0.0), 0.8 * mag[f] / total_mag)
        else:
            for f in members:
                blame[f] = max(blame.get(f, 0.0), share[f] / tot)
    for f in own:
        b = blame.get(f, 0.0)
        fit.outlier[f] = round(min(1.0, b * (0.5 + 0.5 * own[f])) if b > 0 else 0.0, 4)
    return fit


# ----------------------------------------------------------------- the scan's own mistakes
DEFAULT_CONFUSIONS = {
    'substitute': {'5': ['6', '8', '3'], '6': ['5', '8'], '1': ['4', '7'], '4': ['1', '9'], '7': ['1'],
                   '8': ['3', '6', '0'], '3': ['8', '9'], '9': ['4', '3'], '0': ['8', '6'], '2': ['7']},
    'lost_leading_digit': 0.02,
    'decimal_as_comma': 0.01,
    'extra_leading_digit': 0.01,
}


def candidates(value, cal=None, limit=40):
    """What this figure might have been printed as, given how a scan misreads digits.

    Candidates come from undoing one confusion at a time: a substituted digit, a lost leading digit, a decimal read
    as a comma. One edit at a time is deliberate; two edits at once is speculation.
    """
    cal = cal if cal is not None else load_calibration()
    conf = (cal.get('confusions') or DEFAULT_CONFUSIONS)
    subs = conf.get('substitute') or DEFAULT_CONFUSIONS['substitute']
    s = f'{value:.2f}'
    out = {}
    digits = [i for i, c in enumerate(s) if c.isdigit()]
    for i in digits:
        for repl in subs.get(s[i], []):
            t = s[:i] + repl + s[i + 1:]
            try:
                out[float(t)] = out.get(float(t), 0.0) + 1.0 / max(1, len(subs.get(s[i], [])))
            except ValueError:
                pass
    # a lost leading digit: the figure printed was ten times bigger plus a digit
    for d in '123456789':
        t = d + s
        try:
            out.setdefault(float(t), conf.get('lost_leading_digit', 0.02))
        except ValueError:
            pass
    # the decimal read as a comma or dropped: 1173.00 read from 1,173.00 and the like
    if '.' in s:
        whole = s.replace('.', '')
        try:
            out.setdefault(float(whole) / 100.0 * 100.0, conf.get('decimal_as_comma', 0.01))
        except ValueError:
            pass
    out.pop(value, None)
    return dict(sorted(out.items(), key=lambda kv: -kv[1])[:limit])


STATUS_OBSERVED = 'observed'
STATUS_DERIVED = 'derived from the statement\'s own figures and a stated identity'
STATUS_EXPECTED = 'expected from another document, not established'


def fill_derived(rec, cal=None, tolerance=0.02, expectations=None):
    """Figures the statement determines but the scan did not read.

    A figure is filled only where every other figure in one identity was read, so the value follows from the page
    by subtraction. It is returned separately with its status and the identity used, and the caller must keep that
    label: a derived figure is not a figure read from the payroll.
    """
    out = {}
    for name, coeffs in IDENTITIES:
        missing = [f for f in coeffs if rec.get(f) is None]
        if len(missing) != 1:
            continue
        target = missing[0]
        c = coeffs[target]
        if abs(c) < 1e-9:
            continue
        # A line the statement does not print is not a line the statement omitted. Where another document says the
        # figure should be zero, or should not be there at all, solving the identity for it invents a deduction
        # nobody charged: the before statement of a premium arrangement has no premium and no fee.
        exp = (expectations or {}).get(target)
        if exp is not None and abs(exp.value) < 0.01:
            continue
        total = sum(coeffs[f] * float(rec[f]) for f in coeffs if f != target)
        value = round(-total / c, 2)
        if value < -0.01:
            continue
        if exp is not None and exp.auditable and abs(value - exp.value) > 5 * max(exp.sd, 0.01):
            continue                      # the derivation disagrees with the other documents, so it is not reported
        out[target] = dict(value=value, status=STATUS_DERIVED, identity=name,
                           from_fields=[f for f in coeffs if f != target])
    return out


def most_likely_reading(rec, field_name, cal=None, expectations=None, margin=2.0, decisive_at=0.9):
    """The posterior over what a suspect figure was printed as, given the statement's identities.

    Each candidate is scored by how much better it makes the identities fit, weighted by how likely the scan is to
    have made that particular mistake. The result is a posterior over readings, not a correction: nothing here
    changes what the report says was printed.
    """
    cal = cal if cal is not None else load_calibration()
    base = solve(rec, cal)
    if field_name not in base.observed:
        return dict(field=field_name, note='that figure was not read, so there is nothing to reconsider')
    cands = candidates(base.observed[field_name], cal)
    scored = []
    for v, prior in list(cands.items()) + [(base.observed[field_name], 1.0)]:
        trial = dict(rec)
        trial[field_name] = v
        f = solve(trial, cal)
        cross = 0.0
        cross_source = ''
        if expectations:
            from . import crossdoc as X
            cross, cross_source = X.score_candidate(field_name, v, expectations)
        # How badly the statement still fails to tie, in dollars. An absolute measure with a dollar scale is used
        # rather than a squared one in units of the rounding variance: the latter saturates, and every candidate
        # but one then comes out at probability zero, which is a false precision the evidence does not support.
        misfit = sum(abs(r) for r in f.residuals.values())
        scored.append((v, prior, misfit, cross, cross_source))
        del f
    if not scored:
        return dict(field=field_name, note='no alternative reading to consider')
    best = min(m for _, _, m, _, _ in scored)
    temperature = float(cal.get('misfit_temperature') or 5.0)      # dollars: how much misfit is one unit of doubt
    post, total, sources = [], 0.0, {}
    for v, prior, misfit, cross, src in scored:
        # three terms, kept apart on purpose: how likely the scan was to make this mistake, how well the page then
        # ties, and what another document says. The third is only ever a proposal input or a census figure, never
        # an engine output, so the audit cannot converge on the answer it is testing.
        like = math.exp(-(misfit - best) / max(temperature, 0.1) + cross)
        post.append((v, max(prior, 1e-6) * like))
        total += max(prior, 1e-6) * like
        if src:
            sources[round(v, 2)] = src
    post = sorted(((v, p / max(total, 1e-300)) for v, p in post), key=lambda t: -t[1])[:5]
    decisive = (len(post) > 1 and post[0][1] >= decisive_at and post[0][1] > margin * post[1][1])
    return dict(field=field_name, observed=base.observed[field_name], decisive=bool(decisive),
                cross_document_source=sources.get(round(post[0][0], 2), '') if post else '',
                posterior=[dict(value=round(v, 2), probability=round(p, 4)) for v, p in post])


# ----------------------------------------------------------------- how much it matters
def gap_interval(before, after, allotment, pay_periods=12, fee=None, draws=20000, cal=None, seed=12345,
                 materiality=25.0, outliers=None):
    """Monte Carlo on the conclusion: the gap between the promised allotment and the actual net pay change.

    Each draw perturbs the figures that were read by their calibrated error and re-imposes the statement's
    identities by re-solving, so the draws keep the correlations the identities create rather than treating each
    figure as independent. What comes back is a credible interval and the chance the gap is beyond materiality.
    This is a modelled interval. It is not a payroll figure.
    """
    try:
        import numpy as np
    except Exception:
        return dict(note='numpy is not available, so no interval was computed')
    cal = cal if cal is not None else load_calibration()
    if not before or not after or before.get('net_pay') is None or after.get('net_pay') is None:
        return dict(note='both statements need a net pay before an interval can mean anything')
    rng = np.random.default_rng(seed)
    per_month = lambda v: v * (pay_periods / 12.0)
    fields = ('net_pay', 'federal', 'state', 'social_security', 'medicare', 'fee')
    sds = {f: observation_sd(f, None, cal) for f in fields}
    base_rate = float(cal.get('outlier_rate') or 0.05)
    outliers = outliers or {}
    # Two ways a reading can be wrong, and the interval has to carry both: the ordinary cent level noise, and the
    # chance that the figure is not the printed one at all, in which case the draw comes from the alternative
    # readings the scan could have produced. Without the second part the interval is a few cents wide and says
    # nothing useful about a statement that does not tie.
    alt = {}
    for tag, rec in (('b', before), ('a', after)):
        for f in fields:
            v = rec.get(f)
            if v is None:
                continue
            cands = list(candidates(v, cal).items())
            if cands:
                alt[(tag, f)] = cands
    gaps = []
    for _ in range(int(draws)):
        b = dict(before); a = dict(after)
        for tag, rec in (('b', b), ('a', a)):
            for f in fields:
                if rec.get(f) is None:
                    continue
                p_bad = float(outliers.get((tag, f), outliers.get(f, base_rate)))
                if alt.get((tag, f)) and rng.random() < p_bad:
                    vals = [v for v, _ in alt[(tag, f)]]
                    wts = np.array([w for _, w in alt[(tag, f)]], dtype=float)
                    wts = wts / wts.sum() if wts.sum() > 0 else None
                    rec[f] = float(rng.choice(vals, p=wts))
                else:
                    rec[f] = rec[f] + rng.normal(0.0, sds[f])
        actual = per_month((a['net_pay'] - b['net_pay']) + (a.get('product') or 0.0))
        gaps.append(actual - (allotment or 0.0))
    g = np.array(gaps)
    lo, hi = np.percentile(g, [2.5, 97.5])
    p_material = float(np.mean(np.abs(g) > materiality))
    return dict(median=round(float(np.median(g)), 2), low=round(float(lo), 2), high=round(float(hi), 2),
                probability_beyond_materiality=round(p_material, 4), materiality=materiality, draws=int(draws),
                note='modelled interval from the reading uncertainty, not a figure printed on the payroll')
